### ISSUE TITLE
GUI toolkitek

### ISSUE THREAD

**Issue by lipk** [lipk/pyzertz#1]
Python GUI toolkitek keresése és elemzése.

Szóba jöhet widget rendszer (PyQt, PyGTK, stb) és valamilyen grafikus könyvtár (SDL, Allegro) wrapper is.

Szempontok:

* Lehessen custom widgetet csinálni (ablakozó frameworkoknél)
* 2D rajzoló primitívek
* Font renderelés

**Comment by bgd54** [comment]
ok

**Comment by sikba** [comment]
OK

**Comment by lipk** [comment]
Attila szerint a PyQt nagyon rossz ötlet.
