### ISSUE TITLE
Teszt frameworkok

### ISSUE THREAD

**Issue by lipk** [lipk/pyzertz#3]
Utánanézni, hogy milyen teszt frameworkok vannak Pythonhoz, erősségek/gyengeségek.

A feladatkiírás szerint ilyen is kell, szerintem használni nem nagyon fogjuk, úgyhogy az elsődleges szempont az egyszerűség.

**Comment by bgd54** [comment]
Python technológiákon volt tesztelős leőadás. Megpróbálom előkaparni.

**Comment by sikba** [comment]
OK
