### ISSUE TITLE
Coding style guide

### ISSUE THREAD

**Issue by lipk** [lipk/pyzertz#4]
Összeírni a szempontokat, aztán majd együtt döntünk. Utána lehet nézni a hivatalos Python konvencióknak (PEP-8) és lintereknek is.

**Comment by bgd54** [comment]
OK

**Comment by bgd54** [comment]
"lintereket használjatok" Attila

**Comment by lipk** [comment]
Beleírtam.

**Comment by sikba** [comment]
OK
